/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_questdb_std_DoubleConversion */

#ifndef _Included_io_questdb_std_DoubleConversion
#define _Included_io_questdb_std_DoubleConversion
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jint JNICALL Java_io_questdb_std_DoubleConversion_append
  (JNIEnv *, jclass, jlong, jdouble);

JNIEXPORT jdouble JNICALL Java_io_questdb_std_DoubleConversion_parse
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
